# Generated by Django 3.0.4 on 2020-07-16 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='label',
            field=models.CharField(default=2020, max_length=20),
            preserve_default=False,
        ),
    ]
