# Generated by Django 3.1.4 on 2021-07-24 21:47

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_publication_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
        ),
    ]
