# Generated by Django 3.1.4 on 2021-07-24 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_publication_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='description',
        ),
    ]
