# Generated by Django 3.1.4 on 2021-07-24 21:59

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=''),
        ),
    ]
