# Generated by Django 3.0.4 on 2020-07-06 10:10

import ckeditor_uploader.fields
from django.db import migrations, models
import research.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('order', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(default=research.models.get_now_year)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
